[tool.poetry]
name = "ba7besh"
version = "0.1.0"
description = ""
authors = ["Hamza Rabah <h.rabah@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
