name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

env:
  AWS_REGION: eu-central-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Configure AWS credentials
        run: |
          aws configure set region ${{ env.AWS_REGION }}
          export AWS_ROLE_ARN=${{ secrets.AWS_ROLE_ARN }} # To Be Created
          export AWS_WEB_IDENTITY_TOKEN_FILE=$(mktemp)
          echo -n "${{ secrets.GITHUB_TOKEN }}" > $AWS_WEB_IDENTITY_TOKEN_FILE
          aws sts assume-role-with-web-identity --role-arn $AWS_ROLE_ARN --role-session-name GitHubActionsSession --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE > assume-role-output.json
          export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' assume-role-output.json)
          export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' assume-role-output.json)
          export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' assume-role-output.json)

      - name: Build and deploy CDK stack
        run: |
          cd <path_to_cdk_project_directory> # To Be Created
          python -m pip install --upgrade aws-cdk.core
          cdk deploy --app "python main.py" --require-approval never
