name: Deploy to Amazon Beanstalk

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  APPLICATION_NAME: ba7besh-backend
  ENVIRONMENT_NAME: ba7besh-backend-dev


jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Get secrets and create .env file
      run: echo "$ENV_PROD" > .env
      env:
        ENV_PROD: ${{ secrets.ENV_PROD }}

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        application_name: ${{env.APPLICATION_NAME}}
        environment_name: ${{env.ENVIRONMENT_NAME}}
        region: ${{env.AWS_REGION}}
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
        use_existing_version_if_available: true